-- PUBLIC DEMO: spoilers are visible in this repository.
-- Technical test content, NOT the finished game. Import real cases privately.
begin;
insert into deadline_private.cases(slug,title,introduction,solution,duration_seconds) values
('demo-v1','TESTFALL / Sista mötet',
'Ni är gäster på ett kvällsevenemang. Arrangören Johan Voss har hittats död i arkivet klockan 21.20. En av era fiktiva personas är skyldig. Läs era roller privat, presentera era personas och granska bevisen tillsammans. Ingen behöver skådespela. Testet tar 20 minuter. Lämna varsin slutanklagelse innan ni öppnar facit.',
'Alex Berg är skyldig. Loggen visar passerkort A7 i arkivet 21.12–21.18. Den slutliga bevisningen knyter kortet till Alex och utesluter andra ingångar. Johan dog inom samma tidsintervall. Motivet i testberättelsen är det avslutade samarbetet. Detta är ett förenklat systemtest, inte ett färdigbalanserat mysterium.',1200)
on conflict(slug) do update set title=excluded.title,introduction=excluded.introduction,solution=excluded.solution,duration_seconds=excluded.duration_seconds;
insert into deadline_private.roles(case_slug,slot,content) values
('demo-v1',1,'{"name":"Alex Berg","occupation":"Affärspartner","background":"Du och Johan drev ett projekt tillsammans. Johan ville avsluta samarbetet i kväll.","knows":"Du har passerkort A7. Bara du använde det i kväll.","secret":"Du är mördaren. Du gick in i arkivet 21.12 och lämnade det 21.18.","objective":"Undvik att bli utpekad. Du får ljuga om ditt alibi, men inte förfalska eller gömma gemensamma bevis.","is_murderer":true,"rules":"Läs inte upp hela kortet. Du får undanhålla din hemlighet. Gemensamma bevis får aldrig ändras eller gömmas. Följ undantaget i ditt mål när du ljuger."}'::jsonb),
('demo-v1',2,'{"name":"Robin Ek","occupation":"Ekonomiansvarig","background":"Du kontrollerar projektets ekonomi och grälade med Johan om ett försvunnet kvitto.","knows":"Du var i stora salen med Sam från 21.10 till 21.20.","secret":"Du slarvade bort kvittot och försökte dölja det.","objective":"Hitta mördaren utan att ditt slarv tar över diskussionen.","is_murderer":false,"rules":"Läs inte upp hela kortet. Du får undanhålla din hemlighet men inte hitta på fakta eller ändra det du sett. Gemensamma bevis får aldrig ändras eller gömmas."}'::jsonb),
('demo-v1',3,'{"name":"Sam Lind","occupation":"Fotograf","background":"Du dokumenterade kvällens evenemang. Johan ville inte att en viss bild skulle publiceras.","knows":"Du fotograferade Robin i stora salen 21.14.","secret":"Du behöll bilden trots Johans protester. Den visar ett gräl före mordet.","objective":"Hitta mördaren och förklara vad ditt fotografi faktiskt visar.","is_murderer":false,"rules":"Läs inte upp hela kortet. Du får undanhålla din hemlighet men inte hitta på fakta eller ändra det du sett. Gemensamma bevis får aldrig ändras eller gömmas."}'::jsonb),
('demo-v1',4,'{"name":"Kim Dahl","occupation":"Assistent","background":"Du planerade kvällen och hittade Johan i arkivet 21.20.","knows":"Arkivets nödutgång är larmad. Huvudingången registrerar varje passage.","secret":"Du läste ett privat brev där Johan avslutade ett affärssamarbete.","objective":"Hitta mördaren. Du väljer när du berättar om brevet.","is_murderer":false,"rules":"Läs inte upp hela kortet. Du får undanhålla din hemlighet men inte hitta på fakta eller ändra det du sett. Gemensamma bevis får aldrig ändras eller gömmas."}'::jsonb),
('demo-v1',5,'{"name":"Liv Strand","occupation":"Trädgårdsansvarig","background":"Du kom till festen efter ditt arbetspass.","knows":"Du såg Johan och Alex diskutera häftigt strax före klockan 21.","secret":"Du hade bett Johan om ett förskott på din ersättning.","objective":"Hitta mördaren och skilj på ekonomiska problem och bevis.","is_murderer":false,"rules":"Läs inte upp hela kortet. Du får undanhålla din hemlighet men inte hitta på fakta eller ändra det du sett. Gemensamma bevis får aldrig ändras eller gömmas."}'::jsonb),
('demo-v1',6,'{"name":"Charlie Nord","occupation":"Evenemangsansvarig","background":"Du ansvarade för gästlistan.","knows":"Robin och Sam stod tillsammans i stora salen under en del av kvällen.","secret":"Du släppte in en gäst utan biljett tidigare under dagen.","objective":"Hitta mördaren utan att ditt misstag förväxlas med mordet.","is_murderer":false,"rules":"Läs inte upp hela kortet. Du får undanhålla din hemlighet men inte hitta på fakta eller ändra det du sett. Gemensamma bevis får aldrig ändras eller gömmas."}'::jsonb),
('demo-v1',7,'{"name":"Lo West","occupation":"Säkerhetsansvarig","background":"Du ansvarade för passerkorten under evenemanget.","knows":"Varje gäst tilldelades ett personligt passerkort. Den skriftliga listan är mer pålitlig än ditt minne.","secret":"Du kom sent till morgonmötet och ville inte berätta det.","objective":"Hitta mördaren med hjälp av loggarna, inte rykten.","is_murderer":false,"rules":"Läs inte upp hela kortet. Du får undanhålla din hemlighet men inte hitta på fakta eller ändra det du sett. Gemensamma bevis får aldrig ändras eller gömmas."}'::jsonb),
('demo-v1',8,'{"name":"Mika Sjö","occupation":"Journalist","background":"Du intervjuade gästerna om projektet.","knows":"Johan hade sagt att han skulle bryta med en affärspartner.","secret":"Du spelade in intervjun utan att först fråga Johan.","objective":"Hitta mördaren och försök belägga uppgifterna du hör.","is_murderer":false,"rules":"Läs inte upp hela kortet. Du får undanhålla din hemlighet men inte hitta på fakta eller ändra det du sett. Gemensamma bevis får aldrig ändras eller gömmas."}'::jsonb)
on conflict(case_slug,slot) do update set content=excluded.content;
insert into deadline_private.clues(case_slug,sequence,unlock_seconds,title,body) values
('demo-v1',1,0,'01 / Fyndplatsen','Johan hittades i arkivet 21.20. Rummet hade en huvudingång med kortläsare och en larmad nödutgång. Ingen gäst fanns inne i arkivet före Johan.'),
('demo-v1',2,300,'02 / Passageloggen','Johan gick in 21.10. Passerkort A7 registrerades in 21.12 och ut 21.18. Kim gick in 21.20. Inga andra passager finns. Diskutera vem som använde A7.'),
('demo-v1',3,600,'03 / Den slutliga kontrollen','A7 tillhör Alex Berg. Kameragranskningen bekräftar att Alex själv använde kortet och att ingen smet in bakom någon annan. Nödutgången var stängd hela tiden. Undersökningen placerar mordet mellan 21.11 och 21.17. Johan hade samma kväll avslutat samarbetet med Alex.')
on conflict(case_slug,sequence) do update set unlock_seconds=excluded.unlock_seconds,title=excluded.title,body=excluded.body;
commit;
